// <auto-generated />
using System;
using FlightMicroservice.DBContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlightMicroservice.Migrations
{
    [DbContext(typeof(FlightContext))]
    [Migration("20241222093208_UpdateFlightContext")]
    partial class UpdateFlightContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FlightMicroservice.Models.Flight", b =>
                {
                    b.Property<int>("FlightID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FlightID"), 1L, 1);

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FlightID");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            FlightID = 1,
                            DepartureTime = new DateTime(2024, 12, 18, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "New York",
                            FlightNumber = "UA123"
                        },
                        new
                        {
                            FlightID = 2,
                            DepartureTime = new DateTime(2024, 12, 18, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Los Angeles",
                            FlightNumber = "DL456"
                        },
                        new
                        {
                            FlightID = 3,
                            DepartureTime = new DateTime(2024, 12, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Chicago",
                            FlightNumber = "AA789"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
