// <auto-generated />
using System;
using FlightMicroservice.DBContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlightMicroservice.Migrations
{
    [DbContext(typeof(FlightContext))]
    [Migration("20241213165403_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FlightMicroservice.Models.Flight", b =>
                {
                    b.Property<string>("FlightID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FlightID");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            FlightID = "FL001",
                            DepartureTime = new DateTime(2024, 12, 14, 1, 54, 2, 783, DateTimeKind.Local).AddTicks(5291),
                            Destination = "New York",
                            FlightNumber = "UA123"
                        },
                        new
                        {
                            FlightID = "FL002",
                            DepartureTime = new DateTime(2024, 12, 14, 2, 54, 2, 783, DateTimeKind.Local).AddTicks(5401),
                            Destination = "Los Angeles",
                            FlightNumber = "DL456"
                        },
                        new
                        {
                            FlightID = "FL003",
                            DepartureTime = new DateTime(2024, 12, 14, 3, 54, 2, 783, DateTimeKind.Local).AddTicks(5403),
                            Destination = "Chicago",
                            FlightNumber = "AA789"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
